export const SET_ITEMS = "SET_ITEMS";
export const SET_TAGS = "SET_TAGS";
export const SET_COMPANIES = "SET_COMPANIES";
export const SET_SORTING_PARAMS = "SET_SORTING_PARAMS";
export const SET_COMPANY_FILTER = "SET_FILTER";
export const UPDATE_COMPANY_AMOUNTS = "UPDATE_COMPANY_AMOUNTS";
export const UPDATE_TAGS_AMOUNTS = "UPDATE_TAGS_AMOUNTS";
export const SET_TAG_FILTER = "SET_TAG_FILTER";
export const SET_PRODUCT_CATEGORY = "SET_PRODUCT_CATEGORY";
export const SET_LOADING = "SET_LOADING";
export const SET_TOTAL_AMOUNT_FOR_TAGS = "SET_TOTAL_AMOUNT_FOR_TAGS";
export const SET_TOTAL_AMOUNT_FOR_COMPANIES = "SET_TOTAL_AMOUNT_FOR_COMPANIES";
export const SET_TOTAL_ITEM_AMOUNT = "SET_TOTAL_ITEM_AMOUNT";

